name: statemachine
version: 3.3.1

homepage: https://github.com/renggli/dart-statemachine
description: A simple, yet powerful state machine framework for Dart supporting
  Flutter and web apps.
topics:
  - async
  - state
  - state-machine
  - streams

environment:
  sdk: ^3.5.0
dependencies:
  #  Had to change this to 1.15.0 from 1.16.0 because meta is pinned to version 1.15.0 by flutter_test from the flutter SDK.
  # See https://dart.dev/go/sdk-version-pinning for details.
  meta: ^1.15.0   

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^5.0.0
  test: ^1.25.0
  web: ^1.1.0
