name: statemachine
version: 3.3.0

homepage: https://github.com/renggli/dart-statemachine
description: A simple, yet powerful state machine framework for Dart supporting
  Flutter and web apps.

environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  meta: ^1.7.0
dev_dependencies:
  build_runner: ^2.1.0
  build_web_compilers: ^3.2.0
  lints: ^2.0.0
  test: ^1.21.0
